### PR TITLE
Remove last bits of dot-com specific code

### PR DESCRIPTION
**Pull request by VSEphpbb**
One thing will need updating on the main web site:

[This line](https://github.com/phpbb/website-assets/blob/6a18e596d95269408863bb1a42d009f5ed3ae19d/css/navigation.css#L54) should be updated to:
```
body.customise li.but-customise > a,
body.customisation-database li.but-customise > a,
```
After these changes, the only difference between the 32x and 32x-dot-com branches will be the configuration file that is in the dot-com branch

### CODE REVIEW

**Comment by battye** [comment]
@VSEphpbb On your local environment, have you got it set up like .com?
eg. No vendor/ directory in Titania, running `composer install`from the forum root?

If so, would you be able to confirm that the change at https://github.com/phpbb/customisation-db/commit/a43d7b09fad36c4dcf4d081a45ba302d54e2668f no longer causes any composer conflicts?

Thanks

**Comment by VSEphpbb** [comment]
@battye Got this result:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 7 updates, 0 removals
  - Downgrading symfony/yaml (v3.4.26 => v2.8.50): Loading from cache
  - Downgrading symfony/finder (v3.4.26 => v2.8.50): Loading from cache
  - Downgrading symfony/debug (v3.4.26 => v3.0.9): Downloading (100%)         
  - Downgrading symfony/console (v3.4.26 => v2.8.50): Loading from cache
  - Updating battye/php-array-parser (v1.0.4 => v1.0.5): Downloading (100%)         
  - Removing phpbb/translation-validator (1.5.0)
  - Installing phpbb/translation-validator (dev-symfony-2.8 32d91a5): Cloning 32d91a5bbb from cache
  - Updating symfony/filesystem (v3.4.26 => v4.2.7): Downloading (100%)         
Generating autoload files
```

**Comment by VSEphpbb** [comment]
@battye Guess this doesnt help you as no, I do not have anything like dot-com set up locally.

**Comment by VSEphpbb** [comment]
@battye Alright, replaced my forum's composer json and lock files with dot-com's, ran composer from forum root and got this successful result:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 23 installs, 32 updates, 2 removals
  - Removing michelf/php-markdown (1.8.0)
  - Removing sami/sami (v1.4.1)
  - Installing composer/installers (v1.6.0): Loading from cache
  - Updating google/recaptcha (1.1.2 => 1.2.1): Downloading (100%)         
  - Updating nikic/php-parser (v0.9.5 => v3.1.5): Downloading (100%)         
  - Updating react/promise (v2.7.0 => v2.7.1): Loading from cache
  - Updating s9e/text-formatter (0.13.1 => 1.4.2): Loading from cache
  - Updating symfony/polyfill-ctype (v1.9.0 => v1.11.0): Loading from cache
  - Updating symfony/filesystem (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/config (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/polyfill-php55 (v1.9.0 => v1.11.0): Loading from cache
  - Updating symfony/polyfill-php54 (v1.9.0 => v1.11.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.9.0 => v1.11.0): Loading from cache
  - Updating symfony/http-foundation (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/event-dispatcher (v2.8.45 => v2.8.49): Loading from cache
  - Updating psr/log (1.0.2 => 1.1.0): Loading from cache
  - Updating symfony/debug (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/http-kernel (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/dependency-injection (v2.8.45 => v2.8.49): Loading from cache
  - Updating zendframework/zend-eventmanager (2.5.1 => 3.2.1): Downloading (100%)         
  - Updating zendframework/zend-code (2.5.1 => 2.6.3): Downloading (100%)         
  - Updating symfony/proxy-manager-bridge (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/routing (v2.8.45 => v2.8.49): Loading from cache
  - Updating twig/twig (v1.35.4 => v1.39.1): Loading from cache
  - Updating symfony/twig-bridge (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/yaml (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/process (v2.8.45 => v2.8.49): Loading from cache
  - Updating facebook/webdriver (1.1.3 => 1.6.0): Downloading (100%)         
  - Installing webmozart/assert (1.3.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Updating phpdocumentor/reflection-docblock (2.0.5 => 3.3.2): Downloading (100%)         
  - Updating squizlabs/php_codesniffer (2.9.1 => 2.9.2): Loading from cache
  - Updating symfony/dom-crawler (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/browser-kit (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/css-selector (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/finder (v2.8.45 => v2.8.49): Loading from cache
  - Updating symfony/console (v2.8.45 => v2.8.49): Loading from cache
  - Installing seld/phar-utils (1.0.1): Downloading (100%)         
  - Installing seld/jsonlint (1.7.1): Downloading (100%)         
  - Installing justinrainbow/json-schema (5.2.7): Loading from cache
  - Installing composer/xdebug-handler (1.3.0): Downloading (100%)         
  - Installing composer/spdx-licenses (1.4.0): Downloading (100%)         
  - Installing composer/semver (1.4.2): Downloading (100%)         
  - Installing composer/ca-bundle (1.1.2): Downloading (100%)         
  - Installing composer/composer (1.7.2): Downloading (100%)         
  - Installing derky/sortablescaptcha (dev-master 396d10b): Cloning 396d10b81b from cache
  - Installing gitonomy/gitlib (v0.1.8): Downloading (100%)         
  - Installing phpbb/cannedmessages (dev-master 137d752): Cloning 137d752528 from cache
  - Installing phpbb/collapsiblecategories (dev-master f6e57bf): Cloning f6e57bf477 from cache
  - Installing phpbb/ideas (2.2.0): Downloading (100%)         
  - Installing phpbb/teamsecurity (dev-master 131e1ef): Cloning 131e1effe5 from cache
  - Installing sensiolabs/ansi-to-html (v1.1.3): Downloading (100%)         
  - Installing phpbb/epv (dev-master 83e996d): Cloning 83e996d0d8 from cache
  - Installing phpbb/titania (dev-3.2.x-phpbb-com a2d630f): Cloning a2d630fdde from cache
  - Installing phpbb/topicprefixes (dev-master 586d884): Cloning 586d884e0b from cache
  - Installing s9e/phpbb-ext-highlighter (1.2.4): Downloading (100%)         
Generating autoload files
```

**Comment by VSEphpbb** [comment]
It did not install Titania's vendor directory though.

**Comment by battye** [comment]
Thanks @VSEphpbb -- do you know why it might not be installing the Titania vendor directory @DavidIQ?

**Comment by DavidIQ** [comment]
It's not supposed to. It should use the parent's vendor files in this case.

**Comment by VSEphpbb** [comment]
Except Titania requires vendors that are not in the parent.

**Comment by DavidIQ** [comment]
Composer takes care of adding the required packages as would any package manager.

**Comment by VSEphpbb** [comment]
What I mean is, it did not install things...anywhere...like battye/php-array-parser, phpbb/translation-validator or phpbb/epv

**Comment by DavidIQ** [comment]
Don't know why. Try deleting the Titania directory and running composer install again.

**Comment by VSEphpbb** [comment]
I did that

**Comment by VSEphpbb** [comment]
Anyway none of that has anything to do with this PR so should be discussed elsewhere

**Comment by battye** [comment]
@VSEphpbb It's all fixed now on .com. It was an issue to do with dev releases being used and the translation validator repository not being specified... @marc1706 and @DavidIQ got it working tonight.

**Comment by battye** [comment]
Do we need to cherry pick https://github.com/phpbb/customisation-db/commit/f8baf3de3a56ea5a42691911d48331ca98c8b112 and https://github.com/phpbb/customisation-db/commit/a42abfa83508a2533228bce61487268db5e4396b into the `3.2.x` branch?

**Comment by VSEphpbb** [comment]
No

**Comment by DavidIQ** [comment]
Getting rid of the config file would be the next project. It could/should be replaced by an ACP module.

https://github.com/phpbb/website-assets/commit/4cd2b4a098249e6c71bbd2846fcf976b3f7f8f55

Will need to `composer update` the assets.

**Pull request merged**
