### PR TITLE
Support multiple branch selection for revisions

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by paul999** [comment]
You should ask @Raimon if he wants it for styles as well. I can seem to understand why you don't want multiple support for styles.

**Comment by prototech** [comment]
Do not merge. This requires vast more changes than this.

**Comment by VSEphpbb** [comment]
@prototech Glad to see you around. We should get any phpBB 3.2 changes for titania ready, since it's already in beta now :)

**Comment by prototech** [comment]
Of course. Just need to replace my dead laptop and have this tiny bug fixed https://tracker.phpbb.com/browse/PHPBB3-14275

**Comment by Elsensee** [comment]
@prototech See this: https://github.com/phpbb/phpbb/pull/4142
This is already fixed now.

**Comment by DavidIQ** [comment]
@prototech any updates on this?  3.2 is getting awfully close.

**Comment by Derky** [comment]
> Do not merge. This requires vast more changes than just these.

@prototech could you please elaborate on that?

**Comment by michaelcullum** [comment]
@prototech Why can this not be merged please. Thanks.

**Comment by DavidIQ** [comment]
@prototech ping?

**Comment by DavidIQ** [comment]
@VSEphpbb can you make sure this pr is complete and works to the best of your knowledge so we can just merge it? Can't keep waiting any longer on this...

**Comment by VSEphpbb** [comment]
@DavidIQ It was as far as I could figure out from this extension. I have no idea what "vast" other changes could be needed, but my ability to comprehend this extension is impaired. I'm not confident with it being merged based on what prototech said, but then again, I can't figure out what  else needs doing. Should probably have other dev/coders take a look too, maybe they will see something I can't.

**Comment by michaelcullum** [comment]
I can have a look at this before we do the 3.2 upgrade unless you wanted to deploy this pre-3.2 David?

**Comment by Derky** [comment]
@michaelcullum How far are you with the staging server or as faster alternative only an extra database as we discussed? That would really help sorting this out as mentioned before.

**Comment by michaelcullum** [comment]
@Derky That's irrelevant to this. Titania can work fine on a local install. The question is what other changes are needed, why are they needed etc.

**Comment by Derky** [comment]
@michaelcullum I think it would be really helpful to have a staging environment for this, since we can then have multiple team members quickly look through it to see if anything is missing or is breaking in combination with the rest of the site without everyone having to setup Titania and phpBB.com locally.

One of the excuses you used for not fixing the site search was the need for a staging server first, which you would setup in July. So; what's the status now?

**Comment by michaelcullum** [comment]
This is a public place Derky.

**Comment by DavidIQ** [comment]
@VSEphpbb can you rebase this against 3.2.x branch please? Thanks.

**Comment by VSEphpbb** [comment]
@DavidIQ its now on the 3.2.x base branch

**Pull request closed without merging**
