### PR TITLE
Prepare for 3.3 release

### PR DESCRIPTION
**Pull request by marc1706**

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Should there be a 3.3 branch created?

**Comment by marc1706** [comment]
Good question. Yes but no. So this only adds support for submitting 3.3 extensions but it does not add support for phpBB 3.3 to Titania. .com will first move to having 3.3 submissions before actually moving over to 3.3. ;)

**Comment by VSEphpbb** [comment]
@marc1706 I actually meant a Git Branch

**Comment by DavidIQ** [comment]
Not needed right now. Would have to also change the website update script for that

**Comment by marc1706** [comment]
I'd move to a 3.3.x branch when it's actually meant to run on phpBB 3.3.x

**Pull request merged**
