### PR TITLE
apple responsive rank img

### PR DESCRIPTION
**Pull request by hanakin**
Pending tests on area51

### CODE REVIEW

**Comment by hanakin** [comment]
Why was this merged? This will not fix anything this will make everything larger

**Comment by DavidIQ** [comment]
Bigger than it is now _without_ this change???? 😆 

image

You should have closed it then if you knew it was useless. I'll revert.

**Comment by DavidIQ** [comment]
Is there an actual fix coming to correct the abnormality as seen above?

**Comment by hanakin** [comment]
Was not aware this was still an issue on cdb the fix is to remove the media query part for this. The top part is all that is needed which sets them all at 160px

**Pull request merged**
