### PR TITLE
Fix existing phpbb/phpbb requirement in extensions

### PR DESCRIPTION
**Pull request by Nicofuma**

### CODE REVIEW

**Comment by michaelcullum** [comment]
This needs cherry-picking into 3.1.x though

**Comment by DavidIQ** [comment]
You want to do that, or Tristan, or should I take care of it later?


-------- Original message --------

**Comment by Nicofuma** [comment]
Do it please

**Comment by michaelcullum** [comment]
Thanks. I wasn't able to do it earlier as I was just using the web UI.

**Pull request merged**
