### PR TITLE
CUSTDB-680 - Filter contributions by status

### PR DESCRIPTION
**Pull request by battye**
New functionality which allows the user to filter by contribution status (all, approved, unapproved).

ch4

https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-680

### CODE REVIEW

**Comment by VSEphpbb** [comment]
I assume this is only visible to team members?

**Comment by VSEphpbb** [comment]
Non-team members (even unregistred guests) can still see this drop down, and choose approved, unapproved, etc. I think this drop down should only be visible to team members.

**Comment by DavidIQ** [comment]
I missread that part only thinking that the retrieval will not return unapproved items regardless of if the parameter is sent. So yeah the building of the options needs to take into account if the user has queue access to that type. I think not super urgent that needs to be fixed right now since the query to produce the list will exclude by permission anyways.

**Comment by DavidIQ** [comment]
Maybe check how the query is being built to show the contributions list to begin with. There seems to be a differentiation between the general public and a person that has queue access.

**Pull request merged**
