### PR TITLE
Move defined constants to class constants

### PR DESCRIPTION
**Pull request by kasimi**
All constants define()d in `includes/constants.php` were moved to class constants in `ext.php`. The `includes/constants.php` is still there with a `deprecated` message at the top.

I also reverted the commit from earlier (1ed3b21) as it still caused errors when deleting data.

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Since you changed the composer.json file, the composer.lock file will need to be updated here too:

run: `composer update`

**Comment by kasimi** [comment]
Correct, but the `constants.php` file is nowhere mentioned in the `composer.lock` so it doesn't change, unless I messed something up?

**Comment by VSEphpbb** [comment]
Well then I guess it's OK

**Comment by DavidIQ** [comment]
This pr has conflicts now. Please resolve so they can be merged.

**Comment by kasimi** [comment]
Should be ready to be merged now.

**Pull request merged**
